version: '3.8'
services:
  app:
    image: nutriverse-client
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file: '/.env'
    ports:
      - "3000:3000"
    networks:
      - shared-network

networks:
  shared-network:
    external: true